# Welcome to Serverless!

service: hey-office-misc

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  environment:
    TWGUEST_PASSWORD: ${env:TWGUEST_PASSWORD}
    TWEVENT_PASSWORD: ${env:TWEVENT_PASSWORD}
    LEAVE_FORM_LINK: ${env:LEAVE_FORM_LINK}

functions:
  misc:
    handler: handler.misc
